/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.yylc.alcsmng.common.dal.dataobject;

import com.yylc.alcsmng.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>alcs_assign_log</tt>.
 *
 * This file is generated by <tt>yylc-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>yylc</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/alcs_assign_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>yylc-gen-dal</tt> 
 * to generate this file.
 *
 * @author qiang.wq
 * @version $Id: AssignLogDO.java,v 1.0 2013/10/29 07:34:20 qiang.wq Exp $
 */
public class AssignLogDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>case_id</tt>.
	 */
	private int caseId;

	/**
	 * This property corresponds to db column <tt>user_id</tt>.
	 */
	private int userId;

	/**
	 * This property corresponds to db column <tt>period_name</tt>.
	 */
	private String periodName;

	/**
	 * This property corresponds to db column <tt>remark</tt>.
	 */
	private String remark;

	/**
	 * This property corresponds to db column <tt>create_time</tt>.
	 */
	private Date createTime;

	/**
	 * This property corresponds to db column <tt>update_time</tt>.
	 */
	private Date updateTime;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>caseId</tt>.
     *
     * @return property value of caseId
     */
	public int getCaseId() {
		return caseId;
	}
	
	/**
	 * Setter method for property <tt>caseId</tt>.
	 * 
	 * @param caseId value to be assigned to property caseId
     */
	public void setCaseId(int caseId) {
		this.caseId = caseId;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public int getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(int userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>periodName</tt>.
     *
     * @return property value of periodName
     */
	public String getPeriodName() {
		return periodName;
	}
	
	/**
	 * Setter method for property <tt>periodName</tt>.
	 * 
	 * @param periodName value to be assigned to property periodName
     */
	public void setPeriodName(String periodName) {
		this.periodName = periodName;
	}

    /**
     * Getter method for property <tt>remark</tt>.
     *
     * @return property value of remark
     */
	public String getRemark() {
		return remark;
	}
	
	/**
	 * Setter method for property <tt>remark</tt>.
	 * 
	 * @param remark value to be assigned to property remark
     */
	public void setRemark(String remark) {
		this.remark = remark;
	}

    /**
     * Getter method for property <tt>createTime</tt>.
     *
     * @return property value of createTime
     */
	public Date getCreateTime() {
		return createTime;
	}
	
	/**
	 * Setter method for property <tt>createTime</tt>.
	 * 
	 * @param createTime value to be assigned to property createTime
     */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

    /**
     * Getter method for property <tt>updateTime</tt>.
     *
     * @return property value of updateTime
     */
	public Date getUpdateTime() {
		return updateTime;
	}
	
	/**
	 * Setter method for property <tt>updateTime</tt>.
	 * 
	 * @param updateTime value to be assigned to property updateTime
     */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}
