/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.yylc.alcsmng.common.dal.dataobject;

import com.yylc.alcsmng.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>alcs_contact_info</tt>.
 *
 * This file is generated by <tt>yylc-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>yylc</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/alcs_contact_info.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>yylc-gen-dal</tt> 
 * to generate this file.
 *
 * @author qiang.wq
 * @version $Id: ContactInfoDO.java,v 1.0 2013/10/29 07:34:20 qiang.wq Exp $
 */
public class ContactInfoDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>contact_id</tt>.
	 */
	private int contactId;

	/**
	 * This property corresponds to db column <tt>debtor_id</tt>.
	 */
	private int debtorId;

	/**
	 * This property corresponds to db column <tt>phone_num</tt>.
	 */
	private String phoneNum;

	/**
	 * This property corresponds to db column <tt>name</tt>.
	 */
	private String name;

	/**
	 * This property corresponds to db column <tt>relation</tt>.
	 */
	private String relation;

	/**
	 * This property corresponds to db column <tt>call_times</tt>.
	 */
	private int callTimes;

	/**
	 * This property corresponds to db column <tt>call_result</tt>.
	 */
	private String callResult;

	/**
	 * This property corresponds to db column <tt>create_time</tt>.
	 */
	private Date createTime;

	/**
	 * This property corresponds to db column <tt>update_time</tt>.
	 */
	private Date updateTime;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>contactId</tt>.
     *
     * @return property value of contactId
     */
	public int getContactId() {
		return contactId;
	}
	
	/**
	 * Setter method for property <tt>contactId</tt>.
	 * 
	 * @param contactId value to be assigned to property contactId
     */
	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

    /**
     * Getter method for property <tt>debtorId</tt>.
     *
     * @return property value of debtorId
     */
	public int getDebtorId() {
		return debtorId;
	}
	
	/**
	 * Setter method for property <tt>debtorId</tt>.
	 * 
	 * @param debtorId value to be assigned to property debtorId
     */
	public void setDebtorId(int debtorId) {
		this.debtorId = debtorId;
	}

    /**
     * Getter method for property <tt>phoneNum</tt>.
     *
     * @return property value of phoneNum
     */
	public String getPhoneNum() {
		return phoneNum;
	}
	
	/**
	 * Setter method for property <tt>phoneNum</tt>.
	 * 
	 * @param phoneNum value to be assigned to property phoneNum
     */
	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

    /**
     * Getter method for property <tt>name</tt>.
     *
     * @return property value of name
     */
	public String getName() {
		return name;
	}
	
	/**
	 * Setter method for property <tt>name</tt>.
	 * 
	 * @param name value to be assigned to property name
     */
	public void setName(String name) {
		this.name = name;
	}

    /**
     * Getter method for property <tt>relation</tt>.
     *
     * @return property value of relation
     */
	public String getRelation() {
		return relation;
	}
	
	/**
	 * Setter method for property <tt>relation</tt>.
	 * 
	 * @param relation value to be assigned to property relation
     */
	public void setRelation(String relation) {
		this.relation = relation;
	}

    /**
     * Getter method for property <tt>callTimes</tt>.
     *
     * @return property value of callTimes
     */
	public int getCallTimes() {
		return callTimes;
	}
	
	/**
	 * Setter method for property <tt>callTimes</tt>.
	 * 
	 * @param callTimes value to be assigned to property callTimes
     */
	public void setCallTimes(int callTimes) {
		this.callTimes = callTimes;
	}

    /**
     * Getter method for property <tt>callResult</tt>.
     *
     * @return property value of callResult
     */
	public String getCallResult() {
		return callResult;
	}
	
	/**
	 * Setter method for property <tt>callResult</tt>.
	 * 
	 * @param callResult value to be assigned to property callResult
     */
	public void setCallResult(String callResult) {
		this.callResult = callResult;
	}

    /**
     * Getter method for property <tt>createTime</tt>.
     *
     * @return property value of createTime
     */
	public Date getCreateTime() {
		return createTime;
	}
	
	/**
	 * Setter method for property <tt>createTime</tt>.
	 * 
	 * @param createTime value to be assigned to property createTime
     */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

    /**
     * Getter method for property <tt>updateTime</tt>.
     *
     * @return property value of updateTime
     */
	public Date getUpdateTime() {
		return updateTime;
	}
	
	/**
	 * Setter method for property <tt>updateTime</tt>.
	 * 
	 * @param updateTime value to be assigned to property updateTime
     */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}
