/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.yylc.alcsmng.common.dal.dataobject;

import com.yylc.alcsmng.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>alcs_debtor_info</tt>.
 *
 * This file is generated by <tt>yylc-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>yylc</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/alcs_debtor_info.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>yylc-gen-dal</tt> 
 * to generate this file.
 *
 * @author qiang.wq
 * @version $Id: DebtorInfoDO.java,v 1.0 2013/10/29 07:34:20 qiang.wq Exp $
 */
public class DebtorInfoDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>debtor_id</tt>.
	 */
	private int debtorId;

	/**
	 * This property corresponds to db column <tt>name</tt>.
	 */
	private String name;

	/**
	 * This property corresponds to db column <tt>id_num</tt>.
	 */
	private String idNum;

	/**
	 * This property corresponds to db column <tt>phone_num</tt>.
	 */
	private String phoneNum;

	/**
	 * This property corresponds to db column <tt>sex</tt>.
	 */
	private String sex;

	/**
	 * This property corresponds to db column <tt>age</tt>.
	 */
	private int age;

	/**
	 * This property corresponds to db column <tt>census</tt>.
	 */
	private String census;

	/**
	 * This property corresponds to db column <tt>description</tt>.
	 */
	private String description;

	/**
	 * This property corresponds to db column <tt>create_time</tt>.
	 */
	private Date createTime;

	/**
	 * This property corresponds to db column <tt>update_time</tt>.
	 */
	private Date updateTime;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>debtorId</tt>.
     *
     * @return property value of debtorId
     */
	public int getDebtorId() {
		return debtorId;
	}
	
	/**
	 * Setter method for property <tt>debtorId</tt>.
	 * 
	 * @param debtorId value to be assigned to property debtorId
     */
	public void setDebtorId(int debtorId) {
		this.debtorId = debtorId;
	}

    /**
     * Getter method for property <tt>name</tt>.
     *
     * @return property value of name
     */
	public String getName() {
		return name;
	}
	
	/**
	 * Setter method for property <tt>name</tt>.
	 * 
	 * @param name value to be assigned to property name
     */
	public void setName(String name) {
		this.name = name;
	}

    /**
     * Getter method for property <tt>idNum</tt>.
     *
     * @return property value of idNum
     */
	public String getIdNum() {
		return idNum;
	}
	
	/**
	 * Setter method for property <tt>idNum</tt>.
	 * 
	 * @param idNum value to be assigned to property idNum
     */
	public void setIdNum(String idNum) {
		this.idNum = idNum;
	}

    /**
     * Getter method for property <tt>phoneNum</tt>.
     *
     * @return property value of phoneNum
     */
	public String getPhoneNum() {
		return phoneNum;
	}
	
	/**
	 * Setter method for property <tt>phoneNum</tt>.
	 * 
	 * @param phoneNum value to be assigned to property phoneNum
     */
	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

    /**
     * Getter method for property <tt>sex</tt>.
     *
     * @return property value of sex
     */
	public String getSex() {
		return sex;
	}
	
	/**
	 * Setter method for property <tt>sex</tt>.
	 * 
	 * @param sex value to be assigned to property sex
     */
	public void setSex(String sex) {
		this.sex = sex;
	}

    /**
     * Getter method for property <tt>age</tt>.
     *
     * @return property value of age
     */
	public int getAge() {
		return age;
	}
	
	/**
	 * Setter method for property <tt>age</tt>.
	 * 
	 * @param age value to be assigned to property age
     */
	public void setAge(int age) {
		this.age = age;
	}

    /**
     * Getter method for property <tt>census</tt>.
     *
     * @return property value of census
     */
	public String getCensus() {
		return census;
	}
	
	/**
	 * Setter method for property <tt>census</tt>.
	 * 
	 * @param census value to be assigned to property census
     */
	public void setCensus(String census) {
		this.census = census;
	}

    /**
     * Getter method for property <tt>description</tt>.
     *
     * @return property value of description
     */
	public String getDescription() {
		return description;
	}
	
	/**
	 * Setter method for property <tt>description</tt>.
	 * 
	 * @param description value to be assigned to property description
     */
	public void setDescription(String description) {
		this.description = description;
	}

    /**
     * Getter method for property <tt>createTime</tt>.
     *
     * @return property value of createTime
     */
	public Date getCreateTime() {
		return createTime;
	}
	
	/**
	 * Setter method for property <tt>createTime</tt>.
	 * 
	 * @param createTime value to be assigned to property createTime
     */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

    /**
     * Getter method for property <tt>updateTime</tt>.
     *
     * @return property value of updateTime
     */
	public Date getUpdateTime() {
		return updateTime;
	}
	
	/**
	 * Setter method for property <tt>updateTime</tt>.
	 * 
	 * @param updateTime value to be assigned to property updateTime
     */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}
