/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.yylc.alcsmng.common.dal.dataobject;

import com.yylc.alcsmng.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>alcs_user_info</tt>.
 *
 * This file is generated by <tt>yylc-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>yylc</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/alcs_user_info.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>yylc-gen-dal</tt> 
 * to generate this file.
 *
 * @author qiang.wq
 * @version $Id: UserInfoDO.java,v 1.0 2013/10/29 07:34:20 qiang.wq Exp $
 */
public class UserInfoDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>user_id</tt>.
	 */
	private int userId;

	/**
	 * This property corresponds to db column <tt>account</tt>.
	 */
	private String account;

	/**
	 * This property corresponds to db column <tt>password</tt>.
	 */
	private String password;

	/**
	 * This property corresponds to db column <tt>user_name</tt>.
	 */
	private String userName;

	/**
	 * This property corresponds to db column <tt>dept_code</tt>.
	 */
	private int deptCode;

	/**
	 * This property corresponds to db column <tt>location_code</tt>.
	 */
	private int locationCode;

	/**
	 * This property corresponds to db column <tt>user_type</tt>.
	 */
	private int userType;

	/**
	 * This property corresponds to db column <tt>extension</tt>.
	 */
	private String extension;

	/**
	 * This property corresponds to db column <tt>remark</tt>.
	 */
	private String remark;

	/**
	 * This property corresponds to db column <tt>create_time</tt>.
	 */
	private Date createTime;

	/**
	 * This property corresponds to db column <tt>update_time</tt>.
	 */
	private Date updateTime;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public int getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(int userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>account</tt>.
     *
     * @return property value of account
     */
	public String getAccount() {
		return account;
	}
	
	/**
	 * Setter method for property <tt>account</tt>.
	 * 
	 * @param account value to be assigned to property account
     */
	public void setAccount(String account) {
		this.account = account;
	}

    /**
     * Getter method for property <tt>password</tt>.
     *
     * @return property value of password
     */
	public String getPassword() {
		return password;
	}
	
	/**
	 * Setter method for property <tt>password</tt>.
	 * 
	 * @param password value to be assigned to property password
     */
	public void setPassword(String password) {
		this.password = password;
	}

    /**
     * Getter method for property <tt>userName</tt>.
     *
     * @return property value of userName
     */
	public String getUserName() {
		return userName;
	}
	
	/**
	 * Setter method for property <tt>userName</tt>.
	 * 
	 * @param userName value to be assigned to property userName
     */
	public void setUserName(String userName) {
		this.userName = userName;
	}

    /**
     * Getter method for property <tt>deptCode</tt>.
     *
     * @return property value of deptCode
     */
	public int getDeptCode() {
		return deptCode;
	}
	
	/**
	 * Setter method for property <tt>deptCode</tt>.
	 * 
	 * @param deptCode value to be assigned to property deptCode
     */
	public void setDeptCode(int deptCode) {
		this.deptCode = deptCode;
	}

    /**
     * Getter method for property <tt>locationCode</tt>.
     *
     * @return property value of locationCode
     */
	public int getLocationCode() {
		return locationCode;
	}
	
	/**
	 * Setter method for property <tt>locationCode</tt>.
	 * 
	 * @param locationCode value to be assigned to property locationCode
     */
	public void setLocationCode(int locationCode) {
		this.locationCode = locationCode;
	}

    /**
     * Getter method for property <tt>userType</tt>.
     *
     * @return property value of userType
     */
	public int getUserType() {
		return userType;
	}
	
	/**
	 * Setter method for property <tt>userType</tt>.
	 * 
	 * @param userType value to be assigned to property userType
     */
	public void setUserType(int userType) {
		this.userType = userType;
	}

    /**
     * Getter method for property <tt>extension</tt>.
     *
     * @return property value of extension
     */
	public String getExtension() {
		return extension;
	}
	
	/**
	 * Setter method for property <tt>extension</tt>.
	 * 
	 * @param extension value to be assigned to property extension
     */
	public void setExtension(String extension) {
		this.extension = extension;
	}

    /**
     * Getter method for property <tt>remark</tt>.
     *
     * @return property value of remark
     */
	public String getRemark() {
		return remark;
	}
	
	/**
	 * Setter method for property <tt>remark</tt>.
	 * 
	 * @param remark value to be assigned to property remark
     */
	public void setRemark(String remark) {
		this.remark = remark;
	}

    /**
     * Getter method for property <tt>createTime</tt>.
     *
     * @return property value of createTime
     */
	public Date getCreateTime() {
		return createTime;
	}
	
	/**
	 * Setter method for property <tt>createTime</tt>.
	 * 
	 * @param createTime value to be assigned to property createTime
     */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

    /**
     * Getter method for property <tt>updateTime</tt>.
     *
     * @return property value of updateTime
     */
	public Date getUpdateTime() {
		return updateTime;
	}
	
	/**
	 * Setter method for property <tt>updateTime</tt>.
	 * 
	 * @param updateTime value to be assigned to property updateTime
     */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}
