/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.yylc.alcsmng.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.yylc.alcsmng.common.dal.daointerface.RuleInfoDAO;

import com.yylc.alcsmng.common.dal.dataobject.RuleInfoDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.yylc.alcsmng.common.dal.daointerface.RuleInfoDAO</tt>.
 *
 * This file is generated by <tt>yylc-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>yylc</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/alcs_rule_info.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>yylc-gen-dal</tt> 
 * to generate this file.
 *
 * @author qiang.wq
 * @version $Id: IbatisRuleInfoDAO.java,v 1.0 2013/10/29 07:34:20 qiang.wq Exp $
 */
public class IbatisRuleInfoDAO extends SqlMapClientDaoSupport implements RuleInfoDAO {
	/**
	 *  Query DB table <tt>alcs_rule_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_rule_info</tt>
	 *
	 *	@param locationCode
	 *	@return List<RuleInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<RuleInfoDO> selectM0ByLocationCode(int locationCode) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("locationCode", new Integer(locationCode));

        return getSqlMapClientTemplate().queryForList("MS-RULE-INFO-SELECT-M-0-BY-LOCATION-CODE", param);

    }

	/**
	 *  Insert one <tt>RuleInfoDO</tt> object to DB table <tt>alcs_rule_info</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into alcs_rule_info(rule_id,user_id,user_name,location_code,rule_type_code,rule_name,create_time,update_time) values (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param ruleInfo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int saveRuleInfo(RuleInfoDO ruleInfo) throws DataAccessException {
    	if (ruleInfo == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-RULE-INFO-SAVE-RULE-INFO", ruleInfo);

        return ruleInfo.getRuleId();
    }

	/**
	 *  Delete records from DB table <tt>alcs_rule_info</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from alcs_rule_info where (rule_id = ?)</tt>
	 *
	 *	@param ruleId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByRuleId(int ruleId) throws DataAccessException {
        Integer param = new Integer(ruleId);

        return getSqlMapClientTemplate().delete("MS-RULE-INFO-DELETE-BY-RULE-ID", param);
    }

	/**
	 *  Query DB table <tt>alcs_rule_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_rule_info where (rule_id = ?)</tt>
	 *
	 *	@param ruleId
	 *	@return RuleInfoDO
	 *	@throws DataAccessException
	 */	 
    public RuleInfoDO queryRuleByRuleId(int ruleId) throws DataAccessException {

        Integer param = new Integer(ruleId);

        return (RuleInfoDO) getSqlMapClientTemplate().queryForObject("MS-RULE-INFO-QUERY-RULE-BY-RULE-ID", param);

    }

	/**
	 *  Query DB table <tt>alcs_rule_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_rule_info</tt>
	 *
	 *	@param offset
	 *	@param limit
	 *	@return List<RuleInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<RuleInfoDO> pageRuleForAdmin(int offset, int limit) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("offset", new Integer(offset));
        param.put("limit", new Integer(limit));

        return getSqlMapClientTemplate().queryForList("MS-RULE-INFO-PAGE-RULE-FOR-ADMIN", param);

    }

	/**
	 *  Query DB table <tt>alcs_rule_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_rule_info</tt>
	 *
	 *	@param teamLeaderId
	 *	@return List<RuleInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<RuleInfoDO> selectByTeamLeaderId(String teamLeaderId) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("teamLeaderId", teamLeaderId);

        return getSqlMapClientTemplate().queryForList("MS-RULE-INFO-SELECT-BY-TEAM-LEADER-ID", param);

    }

	/**
	 *  Query DB table <tt>alcs_rule_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(1) from alcs_rule_info</tt>
	 *
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int pageCountForAdmin() throws DataAccessException {


	    Integer retObj = (Integer) getSqlMapClientTemplate().queryForObject("MS-RULE-INFO-PAGE-COUNT-FOR-ADMIN", null);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.intValue();
		}

    }

	/**
	 *  Query DB table <tt>alcs_rule_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(1) from alcs_rule_info</tt>
	 *
	 *	@param locationCode
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectForPageCount(int locationCode) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("locationCode", new Integer(locationCode));

	    Integer retObj = (Integer) getSqlMapClientTemplate().queryForObject("MS-RULE-INFO-SELECT-FOR-PAGE-COUNT", param);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.intValue();
		}

    }

	/**
	 *  Query DB table <tt>alcs_rule_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_rule_info</tt>
	 *
	 *	@param locationCode
	 *	@param deptCode
	 *	@param offset
	 *	@param limit
	 *	@return List<RuleInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<RuleInfoDO> selectForPage(int locationCode, int deptCode, int offset, int limit) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("locationCode", new Integer(locationCode));
        param.put("deptCode", new Integer(deptCode));
        param.put("offset", new Integer(offset));
        param.put("limit", new Integer(limit));

        return getSqlMapClientTemplate().queryForList("MS-RULE-INFO-SELECT-FOR-PAGE", param);

    }

}