/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.yylc.alcsmng.common.dal.daointerface;

import com.yylc.alcsmng.common.dal.dataobject.AssignInfoDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>alcs_assign_info</tt>.
 *
 * This file is generated by <tt>yylc-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>yylc</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/alcs_assign_info.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>yylc-gen-dal</tt> 
 * to generate this file.
 *
 * @author qiang.wq
 * @version $Id: AssignInfoDAO.java,v 1.0 2013/10/29 07:34:20 qiang.wq Exp $
 */
public interface AssignInfoDAO {
	/**
	 *  Query DB table <tt>alcs_assign_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_assign_info where (user_id = ?)</tt>
	 *
	 *	@param userId
	 *	@return List<AssignInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<AssignInfoDO> queryByUserId(int userId) throws DataAccessException;

	/**
	 *  Insert one <tt>AssignInfoDO</tt> object to DB table <tt>alcs_assign_info</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into alcs_assign_info(id,case_id,user_id,remark,create_time,update_time) values (?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param assignInfo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int saveAssignInfo(AssignInfoDO assignInfo) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>alcs_assign_info</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete alcs_assign_info</tt>
	 *
	 *	@param caseIdList
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteAssignByCaseIdList(List caseIdList) throws DataAccessException;

	/**
	 *  Query DB table <tt>alcs_assign_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_assign_info</tt>
	 *
	 *	@param offset
	 *	@param limit
	 *	@return List<AssignInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<AssignInfoDO> pageM0ForAdmin(int offset, int limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>alcs_assign_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from alcs_assign_info</tt>
	 *
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int countM0ForAdmin() throws DataAccessException;

	/**
	 *  Query DB table <tt>alcs_assign_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_assign_info</tt>
	 *
	 *	@param userIdList
	 *	@param assignType
	 *	@param offset
	 *	@param limit
	 *	@return List<AssignInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<AssignInfoDO> selectForPage(List userIdList, int assignType, int offset, int limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>alcs_assign_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_assign_info</tt>
	 *
	 *	@param userIdList
	 *	@param assignType
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectForPageCount(List userIdList, int assignType) throws DataAccessException;

}