/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.yylc.alcsmng.common.dal.daointerface;

import com.yylc.alcsmng.common.dal.dataobject.CallRecordDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>alcs_call_record</tt>.
 *
 * This file is generated by <tt>yylc-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>yylc</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/alcs_call_record.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>yylc-gen-dal</tt> 
 * to generate this file.
 *
 * @author qiang.wq
 * @version $Id: CallRecordDAO.java,v 1.0 2013/10/29 07:34:20 qiang.wq Exp $
 */
public interface CallRecordDAO {
	/**
	 *  Query DB table <tt>alcs_call_record</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_call_record</tt>
	 *
	 *	@param caseId
	 *	@param offset
	 *	@param limit
	 *	@return List<CallRecordDO>
	 *	@throws DataAccessException
	 */	 
    public List<CallRecordDO> listRecordByCaseId(int caseId, int offset, int limit) throws DataAccessException;

	/**
	 *  Insert one <tt>CallRecordDO</tt> object to DB table <tt>alcs_call_record</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into alcs_call_record(id,case_id,contact_id,record,call_result,caller_name,phone_num,create_time,update_time) values (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param callRecord
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int saveCallRecord(CallRecordDO callRecord) throws DataAccessException;

	/**
	 *  Query DB table <tt>alcs_call_record</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(1) from alcs_call_record where (case_id = ?)</tt>
	 *
	 *	@param caseId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectForPageCount(int caseId) throws DataAccessException;

}