/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.yylc.alcsmng.common.dal.daointerface;

import java.util.List;
import com.yylc.alcsmng.common.dal.dataobject.CaseInfoDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>alcs_case_info</tt>.
 *
 * This file is generated by <tt>yylc-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>yylc</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/alcs_case_info.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>yylc-gen-dal</tt> 
 * to generate this file.
 *
 * @author qiang.wq
 * @version $Id: CaseInfoDAO.java,v 1.0 2013/10/29 07:34:20 qiang.wq Exp $
 */
public interface CaseInfoDAO {
	/**
	 *  Query DB table <tt>alcs_case_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_case_info</tt>
	 *
	 *	@param caseIdList
	 *	@param offset
	 *	@param limit
	 *	@return List<CaseInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<CaseInfoDO> queryByCaseIdList(List caseIdList, int offset, int limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>alcs_case_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_case_info</tt>
	 *
	 *	@param userIdList
	 *	@return List<CaseInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<CaseInfoDO> queryByUserIdList(List userIdList) throws DataAccessException;

	/**
	 *  Query DB table <tt>alcs_case_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_case_info</tt>
	 *
	 *	@return List<CaseInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<CaseInfoDO> queryCaseNotClosed() throws DataAccessException;

	/**
	 *  Query DB table <tt>alcs_case_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_case_info</tt>
	 *
	 *	@return CaseInfoDO
	 *	@throws DataAccessException
	 */	 
    public CaseInfoDO queryCaseNotAssign() throws DataAccessException;

	/**
	 *  Query DB table <tt>alcs_case_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(1) from alcs_case_info</tt>
	 *
	 *	@param caseIdList
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectForPageCount(List caseIdList) throws DataAccessException;

	/**
	 *  Query DB table <tt>alcs_case_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_case_info where (case_id = ?)</tt>
	 *
	 *	@param caseId
	 *	@return CaseInfoDO
	 *	@throws DataAccessException
	 */	 
    public CaseInfoDO queryCaseByCaseId(int caseId) throws DataAccessException;

	/**
	 *  Update DB table <tt>alcs_case_info</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update alcs_case_info set current_result=? where (case_id = ?)</tt>
	 *
	 *	@param caseInfo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateCaseForCurrentResult(CaseInfoDO caseInfo) throws DataAccessException;

	/**
	 *  Update DB table <tt>alcs_case_info</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update alcs_case_info set days_overdue=? where (case_id = ?)</tt>
	 *
	 *	@param caseInfo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateCaseForDaysOverdue(CaseInfoDO caseInfo) throws DataAccessException;

	/**
	 *  Query DB table <tt>alcs_case_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_case_info</tt>
	 *
	 *	@return List<CaseInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<CaseInfoDO> queryCaseForM1() throws DataAccessException;

}