/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.yylc.alcsmng.common.dal.daointerface;

import com.yylc.alcsmng.common.dal.dataobject.ContactInfoDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>alcs_contact_info</tt>.
 *
 * This file is generated by <tt>yylc-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>yylc</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/alcs_contact_info.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>yylc-gen-dal</tt> 
 * to generate this file.
 *
 * @author qiang.wq
 * @version $Id: ContactInfoDAO.java,v 1.0 2013/10/29 07:34:20 qiang.wq Exp $
 */
public interface ContactInfoDAO {
	/**
	 *  Query DB table <tt>alcs_contact_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from alcs_contact_info</tt>
	 *
	 *	@param debtorId
	 *	@param offset
	 *	@param limit
	 *	@return List<ContactInfoDO>
	 *	@throws DataAccessException
	 */	 
    public List<ContactInfoDO> listByDebtorId(int debtorId, int offset, int limit) throws DataAccessException;

	/**
	 *  Update DB table <tt>alcs_contact_info</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update alcs_contact_info set call_result=?, call_times=(call_times + 1) where (contact_id = ?)</tt>
	 *
	 *	@param contactInfo
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateForCallResult(ContactInfoDO contactInfo) throws DataAccessException;

	/**
	 *  Query DB table <tt>alcs_contact_info</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(1) from alcs_contact_info where (debtor_id = ?)</tt>
	 *
	 *	@param debtorId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int selectForPageCount(int debtorId) throws DataAccessException;

}